services:
  openvpn:
    image: kylemanna/openvpn
    container_name: openvpn
    cap_add:
      - NET_ADMIN
    ports:
      - "10443:10443/tcp"
    volumes:
      - ./openvpn-data:/etc/openvpn
    sysctls:
      net.ipv4.ip_forward: 1
    restart: unless-stopped